name: Auto Repair Trigger - Frontend

on:
  workflow_run:
    workflows: ["Test Frontend"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify ManagerBot
        run: |
          curl -X POST http://${{ secrets.HETZNER_HOST }}:3001/api/managerbot/trigger/codegenbot \
          -H "Content-Type: application/json" \
          -d '{"source": "frontend", "issue": "Test or build failed"}'
