name: Frontend Lint & Test

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint || true

      - name: Run tests
        run: |
          if ! npm run test; then
            echo "❌ Frontend tests failed at $(date -u)" >> .github/frontend-test-failure.log
            exit 1
          fi

      - name: Commit frontend test failure log (if any)
        if: failure()
        run: |
          git config user.name "AI Auto Commit"
          git config user.email "bot@thriveomate.com"
          git add .github/frontend-test-failure.log || true
          git commit -m "⚠️ Frontend test failure logged" || true
          git push || true