# .github/workflows/test.yml
name: Lint & Test

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint || true
      - run: npm run test || true
      - name: Notify ManagerBot on failure
        if: failure()
        run: |
          curl -X POST https://thriveomate.com/api/bots/manager \
          -H "Content-Type: application/json" \
          -d '{"source": "GitHub", "status": "❌ Failure", "workflow": "${{ github.workflow }}", "job": "${{ github.job }}", "branch": "${{ github.ref }}", "commit": "${{ github.sha }}"}'